rest:
  address:
    ip: 0.0.0.0
    port: 2121

scheduler:
  servicePlacement: roundrobin

sla:
  enabled: false
    
messaging:
  connector: nats
  address:
    ip: vm1.jfk.cloud
    port: 4222
  authentication:
    username: nats
    password: T0pS3cr3t
  queues:
    sla: sla-violations
  
database:
  connector: etcd
  address:
    ip: localhost
    port: 4001 
  
cloud:
  datacenters:
  - {id: lax,
     connector: marathon,
     address: {
       ip: vm1.lax.cloud,
       port: 8080}}
  - {id: jfk,
     connector: marathon,
     address: {
       ip: vm1.jfk.cloud,
       port: 8080}}
  - {id: mia,
     connector: marathon,
     address: {
       ip: vm1.mia.cloud,
       port: 8080}}
